// <auto-generated />
using System;
using System.Collections.Generic;
using LctKrasnodarWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LctKrasnodarWebApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20231107120655_AddPartnerInfo")]
    partial class AddPartnerInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LctKrasnodarWebApi.Models.PartnerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AreCardsAndMaterialsDelivered")
                        .HasColumnType("integer");

                    b.Property<int?>("DaysSinceLastCardIssue")
                        .HasColumnType("integer");

                    b.Property<List<double>>("LocationCoordinates")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<int?>("NumberOfApprovedApplications")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfGivenCards")
                        .HasColumnType("integer");

                    b.Property<int?>("WhenPointConnected")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PartnerInfos");
                });

            modelBuilder.Entity("LctKrasnodarWebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
